# Generated by Django 4.2 on 2025-09-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0014_formfield_default_value_formfield_hidden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workflow template',
                'verbose_name_plural': 'Workflow templates',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, help_text='Optional display name', max_length=200)),
                ('role', models.CharField(choices=[('user', 'Risk Representative'), ('dev', 'Risk Champion'), ('ba', 'Risk Approver'), ('pm', 'CRO')], default='user', max_length=10)),
                ('show_in_diagram', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='ticketflow.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Workflow stage',
                'verbose_name_plural': 'Workflow stages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ticketprocess',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='ticketflow.workflowtemplate'),
        ),
    ]
