# Generated by Django 4.2 on 2025-10-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0015_workflowtemplate_workflowstage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowstage',
            options={'ordering': ['template', 'order', 'id'], 'verbose_name': 'Workflow stage', 'verbose_name_plural': 'Workflow stages'},
        ),
        migrations.AlterModelOptions(
            name='workflowtemplate',
            options={'ordering': ['name'], 'verbose_name': 'Workflow template', 'verbose_name_plural': 'Workflow templates'},
        ),
        migrations.AddField(
            model_name='form',
            name='workflow_template',
            field=models.ForeignKey(blank=True, help_text='If set, new requests with this form will use this workflow template by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_forms', to='ticketflow.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticketprocess',
            name='workflow_template',
            field=models.ForeignKey(blank=True, help_text='Template that defined this process route.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='ticketflow.workflowtemplate'),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='role',
            field=models.CharField(choices=[('user', 'Risk Representative'), ('dev', 'Risk Champion'), ('ba', 'Risk Approver'), ('pm', 'CRO')], max_length=16),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='show_in_diagram',
            field=models.BooleanField(default=True, help_text='Whether to show this stage in the workflow diagram view'),
        ),
    ]
